# .github/workflows/web-ci.yml (수정된 버전)
name: Web Frontend CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]  
  workflow_dispatch:

env:
  ACR_NAME: acrdigitalgarage03
  IMAGE_NAME: hiorder/frontend
  MANIFEST_REPO: dg04-hi/hi-manifest
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Clean install dependencies
      run: |
        # package-lock.json 제거 후 새로 생성
        rm -f package-lock.json
        npm install
        
    - name: Run tests
      run: npm test -- --coverage --watchAll=false --passWithNoTests
      
    - name: Build application
      run: npm run build
      
    - name: Generate build timestamp
      id: timestamp
      run: echo "BUILD_TIME=$(date +'%y%m%d%H%M')" >> $GITHUB_OUTPUT
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./deployment/container/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.timestamp.outputs.BUILD_TIME }}
          ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
        
    - name: Output image tags
      run: |
        echo "🎉 Frontend Image pushed successfully!"
        echo "📦 Image: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}"
        echo "🏷️  Tags: ${{ steps.timestamp.outputs.BUILD_TIME }}, latest"

  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Generate build timestamp
      id: timestamp
      run: echo "BUILD_TIME=$(date +'%y%m%d%H%M')" >> $GITHUB_OUTPUT
      
    - name: Checkout manifest repository
      uses: actions/checkout@v4
      with:
        repository: ${{ env.MANIFEST_REPO }}
        token: ${{ secrets.MANIFEST_TOKEN }}
        path: manifest-repo
        
    - name: Update Kubernetes manifest  
      run: |
        cd manifest-repo/web
        sed -i "s|image: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:.*|image: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.timestamp.outputs.BUILD_TIME }}|g" deployment.yaml
        
    - name: Commit and push manifest changes
      run: |
        cd manifest-repo
        git config --local user.email "wjsgksdnf11@naver.com"
        git config --local user.name "hanwool77"
        git add web/deployment.yaml
        git diff --staged --quiet || git commit -m "🚀 Update web frontend image to ${{ steps.timestamp.outputs.BUILD_TIME }}"
        git push